memcached:
  address: 127.0.0.1:11211
eureka:
  instance:
    hostname: manager.sinfonia.heiha.com
  client:
    serviceUrl:
      defaultZone: http://eureka.sinfonia.heiha.com:20089/eureka/
heiha:
  sinfonia:
    service:
      uc:
        host: uc.sinfonia.heiha.com
        port: 20080
      manager:
        host: manager.sinfonia.heiha.com
        port: 80
spring:
  thymeleaf:
    cache: false
